;PER SYSTEM FILE THAT RECORDS THE SYSTEM WIDE DEVICE NUMBERS
;THERE IS ONE OF THESE FOR EACH MOSTBL-1.MAC, OF WHICH THERE
;SHOULD BE ONE FOR EACH SOFTWARE/HARDWARE SYSTEM PAIR.
;
;NOTE THAT TTY'S MUST START AT 2 OR OPCON BREAKS UNLESS YOU
;REASSEMBLE IT ON A PER SYSTEM BASIS (KLUDGE)


	.NLIST

	.MACRO	$DFDEV			;DEFINE DEVICE NUMBERS 

DV.SNK	=	1			;NULL OUTPUT SINK DEVICE
DV.TTY	=	2			;TERMINAL LINES - DON'T CHANGE THIS
DV.CTY	=	DV.TTY+4;12		;PROCESS CONTROLLING PSEUDO-TERMINALS
DV.LNI	=	DV.CTY+2		;LNI'S
DV.PRI	=	-1			;PRIMARY INPUT DEVICE
DV.PRO	=	-2			;PRIMARY OUTPUT DEVICE

	.ENDM	$DFDEV
